package:
  name: "confbusterplusplus"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/e-dang/ConfBusterPlusPlus.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  host:
    - python
    - rdkit 2020_03_3
    - openbabel openbabel-3-1-1
    - numpy >=1.18.1
    - matplotlib >=3.1.1
    - pandas >= 0.24.2
    - seaborn >= 0.9.0

  run:
    - python
    - rdkit 2020_03_3
    - openbabel openbabel-3-1-1
    - numpy >=1.18.1
    - matplotlib >=3.1.1
    - pandas >= 0.24.2
    - seaborn >= 0.9.0

about:
  home: https://github.com/e-dang/ConfBusterPlusPlus.git
  license: MIT
